version: "2"
services:


  eureka_1:
    container_name: eureka1
    build:
      context: eureka
    image: eureka
    hostname: eureka1.docker
    ports:
      - "8762:8761"
    networks:
      - services-network
    environment:
      PEERING_URL: http://eureka2.docker:8761
      HOSTNAME: host.docker.internal
      URL: "http://host.docker.internal:8762"
      PORT: 8762
      VIRTUAL_HOSTNAME: "http://host.docker.internal:8762"

  eureka_2:
    container_name: eureka2
    build:
      context: eureka
    image: eureka
    hostname: eureka2.docker
    ports:
      - "8763:8761"
    networks:
      - services-network
    environment:
      PEERING_URL: http://eureka1.docker:8761
      HOSTNAME: host.docker.internal
      PORT: 8763
      URL: "http://host.docker.internal:8763"
      VIRTUAL_HOSTNAME: "http://host.docker.internal:8763"

  spring-boot:
    container_name: spring-boot
    build:
      context: spring-appp
    image: spring-boot
    ports:
      - "8080:8080"
    networks:
      - services-network
    environment:
      EUREKA_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka

  standalone:
    container_name: standalone
    build:
      context: standalone
    image: standalone
    ports:
      - "8081:8080"
    networks:
      - services-network

networks:
  services-network:
    driver: bridge