version: "2"
services:


  eureka_1:
    container_name: eureka1
    build:
      context: eureka
    image: eureka
    hostname: eureka1.docker
    ports:
      - "8762:8761"
    networks:
      - services-network
    environment:
      PEERING_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka
      HOSTNAME: host.docker.internal
      URL: "http://host.docker.internal:8762"
      PORT: 8762
      VIRTUAL_HOSTNAME: "http://host.docker.internal:8762"

  eureka_2:
    container_name: eureka2
    build:
      context: eureka
    image: eureka
    hostname: eureka2.docker
    ports:
      - "8763:8761"
    networks:
      - services-network
    environment:
      PEERING_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka
      HOSTNAME: host.docker.internal
      PORT: 8763
      URL: "http://host.docker.internal:8763"
      VIRTUAL_HOSTNAME: "http://host.docker.internal:8763"

  spring-boot1:
    container_name: spring-boot1
    build:
      context: springbootapp
    image: spring-boot
    ports:
      - "8080:8080"
    networks:
      - services-network
    environment:
      EUREKA_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka
      EUREKA: eureka1.docker:8761
      APPNAME: springboot1

  spring-boot2:
    container_name: spring-boot2
    build:
      context: springbootapp
    image: spring-boot
    ports:
      - "8081:8080"
    networks:
      - services-network
    environment:
      EUREKA_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka
      EUREKA: eureka1.docker:8761
      APPNAME: springboot2

  spring-boot3:
    container_name: spring-boot3
    build:
      context: springbootapp
    image: spring-boot
    ports:
      - "8082:8080"
    networks:
      - services-network
    environment:
      EUREKA_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka
      EUREKA: eureka1.docker:8761
      APPNAME: springboot3

  spring-boot4:
    container_name: spring-boot4
    build:
      context: springbootapp
    image: spring-boot
    ports:
      - "8083:8080"
    networks:
      - services-network
    environment:
      EUREKA_URL: http://eureka1.docker:8761/eureka,http://eureka2.docker:8761/eureka
      EUREKA: eureka1.docker:8761
      APPNAME: springboot4

networks:
  services-network:
    driver: bridge