GET http://localhost:8081/items

###

POST http://localhost:8081/items
Content-Type: application/json

{
  "category": "smartphone",
  "name": "some name",
  "price": 12345,
  "dateOfAddition": "2021-01-01",
  "size": "10 x 10 x 10",
  "color": "black",
  "weight": 122
}

###
PATCH http://localhost:8081/items/10
Content-Type: application/json

{
  "name": "name2"
}

###
GET http://localhost:8082/users

###
GET http://localhost:8089/orders

