server:
  port: 8761
eureka:
  instance:
    hostname: ${HOSTNAME}
    prefer-ip-address: true
    virtual-host-name: ${VIRTUAL_HOSTNAME}
    status-page-url: ${URL}
  client:
    service-url:
      defaultZone: ${PEERING_URL}/eureka